CREATE TABLE T_TESTE_DDL (

    CD_TESTE    NUMBER(3)       NOT NULL,
    NM_TESTE    VARCHAR2(30)    NOT NULL,
    DS_TESTE    VARCHAR2(60)        NULL,
    DT_TESTE    DATE                NULL
);

ALTER TABLE T_TESTE_DDL ADD CONSTRAINT PK_TESTE_DDL PRIMARY KEY (CD_TESTE);

ALTER TABLE T_TESTE_DDL ADD CONSTRAINT UN_TESTE_NOME UNIQUE (NM_TESTE);
ALTER TABLE T_TESTE_DDL ADD CONSTRAINT UN_TESTE_DESC UNIQUE (DS_TESTE);

COMMIT;