DROP TABLE T_TABLE_DDL_AUTO CASCADE CONSTRAINTS;

CREATE TABLE T_TABLE_DDL_AUTO(
    CD_TESTE NUMBER(3) GENERATED ALWAYS AS IDENTITY,
    NM_TESTE VARCHAR(30)
);

INSERT INTO T_TABLE_DDL_AUTO (NM_TESTE) VALUES ('TESTE AUTO');


SELECT * FROM T_TABLE_DDL_AUTO;