SELECT * FROM T_SIP_DEPTO;

INSERT INTO T_SIP_DEPTO (CD_DEPTO, NM_DEPTO, SG_DEPTO)
VALUES (1,'FINANCEIRO', 'FIN');

INSERT INTO T_SIP_DEPTO (CD_DEPTO, NM_DEPTO, SG_DEPTO)
VALUES (2,'TI', 'TI');

--DCL

COMMIT;

ALTER TABLE T_SIP_PROJETO RENAME COLUMN DT_INCIIO TO DT_INICIO;

INSERT INTO T_SIP_PROJETO (CD_PROJETO, NM_PROJETO, DT_INICIO, DT_TERMINO)
VALUES (2,'CHALLENGE2', TO_DATE('05/09/2024', 'DD/MM/YYYY'), TO_DATE('16/09/2024', 'DD/MM/YYYY'));

INSERT INTO T_SIP_PROJETO (CD_PROJETO, NM_PROJETO, DT_INICIO, DT_TERMINO)
VALUES (1,'CHALLENGE', TO_DATE('05/09/2024', 'DD/MM/YYYY'), TO_DATE('16/09/2024', 'DD/MM/YYYY'));

INSERT INTO T_SIP_PROJETO (CD_PROJETO, NM_PROJETO, DT_INICIO, DT_TERMINO)
VALUES (4,'CHALLENGE4', TO_DATE('05/09/2024', 'DD/MM/YYYY'), NULL );

DESCRIBE T_SIP_PROJETO;

SELECT * FROM T_SIP_PROJETO; 

COMMIT;



--COPIAR LINHAS DE UMA TABELA PARA OUTRA 

CREATE TABLE T_COPY_SIP_PROJETO AS 
SELECT * FROM T_SIP_PROJETO WHERE 1=2;

SELECT * FROM T_COPY_SIP_PROJETO; 

--PROJETOS CONCLUÍDOS CRIAR TABELA REPETIDA
INSERT INTO T_COPY_SIP_PROJETO (CD_PROJETO, NM_PROJETO, DT_INICIO, DT_TERMINO)
(SELECT CD_PROJETO, NM_PROJETO, DT_INICIO, DT_TERMINO
    FROM T_SIP_PROJETO
    WHERE DT_TERMINO IS NOT NULL);
    
--EX02 COLOCAR DADOS NA TABELA 
INSERT INTO T_COPY_SIP_PROJETO (CD_PROJETO, NM_PROJETO, DT_INICIO, DT_TERMINO)
(SELECT *
    FROM T_SIP_PROJETO
    WHERE DT_TERMINO IS NOT NULL);

DROP TABLE T_COPY_SIP_PROJETO;

--EX03 CRIAR TABELA JÁ COM DADOS COPIADOS
CREATE TABLE T_COPY_SIP_PROJETO AS
(SELECT *
    FROM T_SIP_PROJETO
    WHERE DT_TERMINO IS NOT NULL);
    
--UPDATE COM SUBQUERY
SELECT * FROM T_SIP_PROJETO;
UPDATE T_SIP_PROJETO
SET DT_TERMINO = (SELECT DT_TERMINO FROM T_SIP_PROJETO WHERE CD_PROJETO = 1)
WHERE DT_TERMINO IS NULL;

INSERT INTO T_SIP_FUNCIONARIO
VALUES (1, 2, 'MARIA', TO_DATE('01/02/1975', 'DD/MM/YYYY'),
TO_DATE('01/02/1975', 'DD/MM/YYYY'), 54542.54);
 
UPDATE T_SIP_FUNCIONARIO
SET NM_FUNCIONARIO = 'JOSÉ',
    DT_NASCIMENTO = TO_DATE('01/02/1965', 'DD/MM/YYYY')
WHERE NR_MATRICULA = 1;

SELECT TO_CHAR(DT_NASCIMENTO, 'DD/MM/YYYY') FROM T_SIP_FUNCIONARIO ;

UPDATE T_SIP_FUNCIONARIO
SET VL_SALARIO = VL_SALARIO * 1.055
WHERE NR_MATRICULA = 1;

SELECT * FROM T_SIP_FUNCIONARIO;


DELETE FROM T_SIP_FUNCIONARIO
WHERE NR_MATRICULA = 1;

ROLLBACK; 

DELETE FROM T_SIP_DEPTO;
DROP TABLE T_SIP_DEPTO CASCADE CONSTRAINTS;
