ALTER SESSION SET NLS_DATE_FORMAT = 'dd/mm/yyyy hh24:mi:ss';

--T_SIP_DEPTO
INSERT INTO T_SIP_DEPTO (CD_DEPTO, NM_DEPTO, SG_DEPTO)
VALUES (1,'FINANCEIRO','FIN');

INSERT INTO T_SIP_DEPTO (CD_DEPTO, NM_DEPTO, SG_DEPTO)
VALUES (2,'TI','TI');

--DCL
COMMIT;

SELECT * FROM T_SIP_DEPTO;

--T_SIP_PROJETO
ALTER TABLE T_SIP_PROJETO RENAME COLUMN DT_INCIIO TO DT_INICIO;

INSERT INTO T_SIP_PROJETO (CD_PROJETO, NM_PROJETO, DT_INICIO, DT_TERMINO)
VALUES (1, 'FIAP_01', TO_DATE('01/02/2023','DD/MM/YYYY'),
TO_DATE('01/02/2024','DD/MM/YYYY'));

INSERT INTO T_SIP_PROJETO (CD_PROJETO, NM_PROJETO, DT_INICIO, DT_TERMINO)
VALUES (2, 'FIAP_02', TO_DATE('01/02/2023','DD/MM/YYYY'),
TO_DATE('01/02/2024','DD/MM/YYYY'));

DESCRIBE T_SIP_PROJETO;

INSERT INTO T_SIP_PROJETO (CD_PROJETO, NM_PROJETO, DT_INICIO)
VALUES (3, 'FIAP_03', TO_DATE('01/02/2023','DD/MM/YYYY'));

INSERT INTO T_SIP_PROJETO (CD_PROJETO, NM_PROJETO, DT_INICIO, DT_TERMINO)
VALUES (4, 'FIAP_04', TO_DATE('01/02/2023','DD/MM/YYYY'), NULL);

COMMIT;

SELECT * FROM T_SIP_PROJETO;

--COPIAR LINHAS DE UMA TABELA PARA OUTRA

CREATE TABLE T_COPY_SIP_PROJETO AS
SELECT * FROM T_SIP_PROJETO WHERE 1=2;

--PROJETOS CONCLUÍDOS
INSERT INTO T_COPY_SIP_PROJETO (CD_PROJETO, NM_PROJETO, DT_INICIO, DT_TERMINO)
(SELECT CD_PROJETO, NM_PROJETO, DT_INICIO, DT_TERMINO
   FROM T_SIP_PROJETO
   WHERE DT_TERMINO IS NOT NULL);

--EX02   
INSERT INTO T_COPY_SIP_PROJETO 
(SELECT *
   FROM T_SIP_PROJETO
   WHERE DT_TERMINO IS NOT NULL);   
   
--EX03
DROP TABLE T_COPY_SIP_PROJETO;
CREATE TABLE T_COPY_SIP_PROJETO AS
SELECT *
   FROM T_SIP_PROJETO
   WHERE DT_TERMINO IS NOT NULL;

SELECT * FROM T_COPY_SIP_PROJETO;

--UPDATE COM SUBQUERY
SELECT * FROM T_SIP_PROJETO;
UPDATE T_SIP_PROJETO
SET DT_TERMINO = (SELECT DT_TERMINO FROM T_SIP_PROJETO WHERE CD_PROJETO = 1);

DESCRIBE T_SIP_FUNCIONARIO;

INSERT INTO T_SIP_FUNCIONARIO 
VALUES (1,2,'MARIA',TO_DATE('01/02/1975','DD/MM/YYYY')
,TO_DATE('01/05/2001','DD/MM/YYYY')
,5423.30);

UPDATE T_SIP_FUNCIONARIO
SET NM_FUNCIONARIO = 'JOSÉ',
    DT_NASCIMENTO = TO_DATE('01/02/1965','DD/MM/YYYY')
WHERE NR_MATRICULA = 1;    

SELECT * FROM T_SIP_FUNCIONARIO;

UPDATE T_SIP_FUNCIONARIO
SET VL_SALARIO = VL_SALARIO * 1.055
WHERE NR_MATRICULA = 1;    

COMMIT;

DELETE FROM T_SIP_FUNCIONARIO
WHERE NR_MATRICULA = 1;

DELETE FROM T_SIP_DEPTO;

DROP TABLE T_SIP_DEPTO CASCADE CONSTRAINTS;

ROLLBACK;


